### ISSUE TITLE
App not starting.

### ISSUE THREAD

**Issue by preston** [HL7-DaVinci/dtr#11]
On `npm start` I get the following. Some sort of package.json missing dependency?

```$ npm start

> dtr@0.0.1 start /Users/preston/Developer/git/davinci-dtr
> webpack-dev-server --config ./webpack.config.dev.js --port 3005

internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/preston/Developer/git/davinci-dtr/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dtr@0.0.1 start: `webpack-dev-server --config ./webpack.config.dev.js --port 3005`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dtr@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by preston** [comment]
Also note the following on `npm i`

```npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})```

**Comment by preston** [comment]
The build pipeline is set up, but I can't continue until the project builds and starts correctly. :-/

It _should_ auto build and deploy, however... I just can't test it.

**Comment by KeeyanGhoreshi** [comment]
This issue should be taken care of with the recent PR.

**Comment by preston** [comment]
@KeeyanGhoreshi Is the service actually starting on port 3005? It is running now but doesn't seem to be responding on that port. (I.e. https://davinci-dtr.logicahealth.org)

**Comment by preston** [comment]
Indeed when I run it locally with `docker run -it --name davinci-dtr -p 3005:3005 --rm hspc/davinci-dtr:latest`, nothing actually appears to be listening on that port.

**Comment by KeeyanGhoreshi** [comment]
This should be addressed with recent commits.  The host name has been changed to 0.0.0.0
